# src/resources/db/models.py
from sqlalchemy import (
    Column, String, Integer, Text, DateTime, ForeignKey, func, text
)
from sqlalchemy.orm import relationship
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.ext.mutable import MutableDict, MutableList
from src.resources.config.settings import Base

class User(Base):
    __tablename__ = "users"
    user_id = Column(String(50), primary_key=True)
    consent_flags = Column(MutableDict.as_mutable(JSONB), server_default=text('{"ai_processing": false}'), nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    travel_requests = relationship("TravelRequest", back_populates="user")
    personal_profile = relationship("PersonalProfile", back_populates="user", uselist=False)  # Relazione 1:1 con profile

class TravelRequest(Base):
    __tablename__ = "travel_requests"
    travel_id = Column(String(50), primary_key=True)
    user_id = Column(String(50), ForeignKey("users.user_id"))
    origin = Column(String(100))  # Allineato a Pydantic
    destination = Column(String(100))  # Allineato
    start_date = Column(String(10))  # Allineato
    end_date = Column(String(10))  # Allineato
    interests = Column(MutableList.as_mutable(JSONB), server_default=text("'[]'::jsonb"), nullable=False)  # Nuovo, da Pydantic
    year_season_or_month = Column(String(50))  # Mantenuto per flessibilità
    additional_notes = Column(Text)
    structured_output = Column(MutableDict.as_mutable(JSONB), server_default=text("'{}'::jsonb"), nullable=False)  # Per serializzare full Pydantic
    raw_llm_response = Column(Text, nullable=True)  # Per raw output Langchain
    messages = Column(MutableList.as_mutable(JSONB), server_default=text("'[]'::jsonb"), nullable=False)
    current_llm_session_id = Column(String(36), nullable=True)
    current_llm_model = Column(String(200), nullable=True)
    current_llm_agent = Column(String(200), nullable=True)
    status = Column(String(20), default="draft")
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    user = relationship("User", back_populates="travel_requests")
    llm_sessions = relationship("LLMSession", back_populates="travel_request", cascade="all, delete-orphan")
    travel_responses = relationship("TravelResponse", back_populates="travel_request", cascade="all, delete-orphan")  # Nuova relazione

class LLMSession(Base):
    __tablename__ = "llm_sessions"
    session_id = Column(String(36), primary_key=True)  # generated by app
    travel_id = Column(String(50), ForeignKey("travel_requests.travel_id"))
    model = Column(String(200), nullable=False)
    agent = Column(String(200))
    session_conversation_id = Column(String(200))
    started_at = Column(DateTime(timezone=True), server_default=func.now())
    ended_at = Column(DateTime(timezone=True))
    session_metadata = Column(
        "metadata",
        MutableDict.as_mutable(JSONB),
        server_default=text("'{}'::jsonb"),
        nullable=False,
    )
    travel_request = relationship("TravelRequest", back_populates="llm_sessions")

class ModerationLog(Base):
    __tablename__ = "moderation_logs"
    log_id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(String(50), ForeignKey("users.user_id"))
    action = Column(String(100))
    details = Column(Text)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

class PersonalProfile(Base):
    __tablename__ = "personal_profiles"
    user_id = Column(String(50), ForeignKey("users.user_id"), primary_key=True)
    name = Column(String(100), nullable=True)  # Nuovo, da Pydantic
    age = Column(Integer, nullable=True)  # Nuovo, da Pydantic
    preferences = Column(MutableList.as_mutable(JSONB), server_default=text("'[]'::jsonb"), nullable=False)  # Allineato a list[str]
    updated_at = Column(DateTime(timezone=True), server_default=func.now())
    user = relationship("User", back_populates="personal_profile")

class TravelResponse(Base):  # Nuova tabella per persistenza separata
    __tablename__ = "travel_responses"
    response_id = Column(String(50), primary_key=True)  # es. "resp-uuid"
    travel_id = Column(String(50), ForeignKey("travel_requests.travel_id"))
    itinerary = Column(MutableList.as_mutable(JSONB), server_default=text("'[]'::jsonb"), nullable=False)
    hotels = Column(MutableList.as_mutable(JSONB), server_default=text("'[]'::jsonb"), nullable=False)
    transport = Column(MutableList.as_mutable(JSONB), server_default=text("'[]'::jsonb"), nullable=False)
    events = Column(MutableList.as_mutable(JSONB), server_default=text("'[]'::jsonb"), nullable=False)
    raw_llm_response = Column(Text, nullable=True)  # Raw per debug
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    travel_request = relationship("TravelRequest", back_populates="travel_responses")